version: "3.9"
services:
  spring-residencias-imagen:
    image: spring-residencias-imagen
    container_name: spring-residencias-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3030"
    networks:
      - Spring-networks
    depends_on:
      - mysql



  mysql:
    image: mysql
    container_name: mysql_bdd
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: resimono
      MYSQL_USER: azahel
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    networks:
      - Spring-networks
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  Spring-networks:
volumes:
  mysql-volume:
